appName: shipping
replicaCount: 1
image:
  repository: 378784712135.dkr.ecr.us-east-1.amazonaws.com/shipping
  pullPolicy: Always

serviceAccount:
  create: true
  annotations: {}

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  limits:
    cpu: 1
    memory: 2600Mi
  requests:
    cpu: 1
    memory: 2600Mi

env:
  name: dev

configmap:
  create: true
  content:
    CART_ENDPOINT: "cart:80"
    DB_HOST: mysql

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

probes:
  initialDelaySeconds: 60
  periodSeconds: 5